### ISSUE TITLE
i try it and not working!!

### ISSUE THREAD

**Issue by mustafa3mahmoud** [ttv20/NliDownloader#1]
hi, i try to use but I think need some updates.

**Comment by rhecht** [comment]
Thanks for letting me know. I noticed that they changed their entire website since the code was tested. The metadata file though does work.

**Comment by rhecht** [comment]
I will continue looking.

**Comment by rhecht** [comment]
> hi, i try to use but I think need some updates.

Hi, to get the script to work, you need to do "npm install" package.json to download the dependencies, then run the script. I just re-tested it and it works.

Take for example: https://www.nli.org.il/he/discover/manuscripts/hebrew-manuscripts/itempage?docId=PNX_MANUSCRIPTS990001218420205171&vid=MANUSCRIPTS&SearchTxt=000121842

The manuscript ID is PNX_MANUSCRIPTS990001218420205171 . In this case there's no "-1" so you would need to add that to see:

https://web.nli.org.il/_layouts/15/NLI.DigitalItemPresentor/Mirador/web.nli.org.il/sites/NLIS/he/_vti_bin/NLI.DigitalItemPresentor/IIIFManifest.svc/GetManifestByDocID/PNX_MANUSCRIPTS990000621610205171-1 . It's interesting because 
"-2" shows a different document completely.
 
In fact the above URL works the same way as https://www.nli.org.il/he/discover/manuscripts/hebrew-manuscripts/itempage?docId=PNX_MANUSCRIPTS990001218420205171-1&vid=MANUSCRIPTS&SearchTxt=000121842 .

Let me know if this helps.

**Comment by ttv20** [comment]
I think I already solved it for someone, but I forgot to push it to the server, I'll try to get to it

**Comment by mustafa3mahmoud** [comment]
Hi @rhecht thanks for your answer.
 
**Here is the URL type that i try with**

https://www.nli.org.il/ar/books/NNL_ALEPH990018914930205171/NLI

> Hi, to get the script to work, you need to do "npm install" package.json to download the dependencies, then run the script. I just re-tested it and it works.

- npm install
- let id = "NNL_ALEPH990030253360205171"
- node index.js

**and I received this error**

```
NliDownloader-master\index.js:126:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by rhecht** [comment]
I get it. Just as I suspected - parts of the website are different and it appears to be a dozen different sites linked together somehow. The link you shared with me isn't a Hebrew "manuscript" and is its own system. In fact, there's a convenient "download" icon you can use instead of this script.

The script works for a different part of the site which you can see here for example: https://www.nli.org.il/he/discover/manuscripts/hebrew-manuscripts

In comparison, Arabic manuscripts (which you would be looking for) link from here (https://www.nli.org.il/ar/discover/manuscripts) to a different website altogether: https://merhav.nli.org.il/primo-explore/search?query=any,contains,NNL&tab=default_tab&tab=unified_tab&tab=default_tab&tab=unified_tab&vid=NLI&vid=NLI&vid=NLI&vid=NLI&mfacet=tlevel,include,online_resources,1&mfacet=rtype,include,manuscript,1&lang=ar_EG&offset=0&_gl=1*17oake9*_ga*MTc3NTUwMDA2OC4xNjgzMTUyMTM3*_ga_8P5PPG5E6Z*MTY4MzI1MjU2Mi4zLjEuMTY4MzI1Mjc0Ny4xLjAuMA..&_ga=2.173850789.788564176.1683246346-1775500068.1683152137

Hope this helps!

**Comment by mustafa3mahmoud** [comment]
i trying something different by looping in the images and downloading it you can see and edit if you want and can this be helpful for other people too

```
const http = require('http');
const fs = require('fs');

const baseUrl = 'http://rosetta.nli.org.il/delivery/DeliveryManagerServlet?dps_func=stream&dps_pid=';


/*
copy url from first image in the book and replace here >
http://rosetta.nli.org.il/delivery/DeliveryManagerServlet?dps_func=stream&dps_pid=FL137833211
*/

// EDIT VALUE ONLY HERE
// after dbs_pid=

// - copy letters and replace it in startLetters = 'here'
const startLetters = 'FL'

// - copy Number and replace it in startNumber = here
const startNumber = 137833211;

// - open last image in the book and copy Number and replace it in endNumber = here
const endNumber = 137834265;

const downloadImages = async () => {
  for (let i = startNumber; i <= endNumber; i++) {
    const url = `${baseUrl}${startLetters}${i}`;
    console.log(`Checking ${url}`);
    try {
      const req = http.get(url, (res) => {
        const contentType = res.headers['content-type'];
        if (!contentType || !contentType.startsWith('image/jpeg')) {
          console.error(`Ignoring ${url} - not a image!`);
          return;
        }
        const filename = `image-${i}.jpg`;
        const fileStream = fs.createWriteStream(filename);
        const chunks = [];
        res.on('data', (chunk) => {
          chunks.push(chunk);
        });
        res.on('end', () => {
          const buffer = Buffer.concat(chunks);
          fs.writeFile(filename, buffer, (err) => {
            if (err) {
              console.error(`Failed to write file ${filename}, error: ${err}`);
              return;
            }
            console.log(`Downloaded ${url} to ${filename}`);
          });
        });
      });
      req.on('error', (err) => {
        console.error(`Failed to download ${url}, error: ${err}`);
      });
    } catch (err) {
      console.error(`Failed to download ${url}, error: ${err}`);
    }
  }
};

downloadImages();
```

**Comment by mustafa3mahmoud** [comment]
Thanks anyway for the good work and idea.
